name: projeto_reminder
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_snake_navigationbar: ^0.6.1
  loading_animation_widget: ^1.3.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.2

  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.33.5
  sqflite: ^2.0.0+3
  path: ^1.8.0
  image_picker: ^0.8.4+4

#  Google things
  syncfusion_flutter_calendar: ^27.2.3
  intl: ^0.19.0
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

